import type { Metadata } from "next";
import "../globals.css";
import {Navbar, Footer} from "@/components";
import { montserrat } from "../font/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        <Navbar/> 
        {children}
        <Footer/> 
      </body>
    </html>
  );
}
