import type { Metadata } from "next";
import "../globals.css";
import {Sidebar} from "@/components";
import { montserrat } from "../font/fonts";
import { ToastProvider } from "@/context/ToastContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased flex`}
      >
        <Sidebar/>
        <main className= "p-2 w-full">
          <ToastProvider>
            {children}
          </ToastProvider>
        </main>
      </body>
    </html>
  );
}
