import type { Metadata } from "next";
import "../globals.css";
import Sidebar from "@/components/Dashboard/sidebar";
import { montserrat } from "../font/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased flex`}
      >
        <Sidebar/>
        <main className= "p-2 w-full">{children}</main>
      </body>
    </html>
  );
}
